// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCofs8UWg2PgEYWWNWb0hbXTq2L-KVESgs',
    appId: '1:348458736836:android:03e4ed85eb1b811196fd91',
    messagingSenderId: '348458736836',
    projectId: 'udemy-flutter-course-aa1d8',
    storageBucket: 'udemy-flutter-course-aa1d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvyygOoHG4yRijsiEWcFufSnsDnpuMJXM',
    appId: '1:348458736836:ios:bbf785c0c754bbce96fd91',
    messagingSenderId: '348458736836',
    projectId: 'udemy-flutter-course-aa1d8',
    storageBucket: 'udemy-flutter-course-aa1d8.appspot.com',
    androidClientId: '348458736836-n1bdo6m8alck0pp4a0o671t99gcj3uet.apps.googleusercontent.com',
    iosClientId: '348458736836-5r6tu6vblisrs0g14h6nc9u6k19prkpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationProject',
  );
}
